services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local